# Basic
title: Dc's Blog
subtitle: 岁月绵长，要对爱的事不遗余力
welcome_message: 生活分享，技术交流
description: 
creator: 

url: "https://ghotsboyd.github.io/"



# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 博客访问


# Navigation buttons in the front page.
nav:
    - {title: 介绍, description: 自我介绍, url: '/intro'}
    - {title: 兴趣, description: 兴趣爱好, url: '/interesting'}
    - {title: 生活, description: 生活环境, url: '/Life'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: GhotsboyD
    twitter: 
    gplus: 107108267983477358170
    mail: ghotsboy@outlook.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
